Ticket5
RossLockhart/ross-fe-games pull request #2
Opened 2022-09-28 13:53 UTC by RossLockhart

2022-09-28 14:07 UTC, mallionaire requested changes
Really great start, there are a few comments dotted about for you to think about. 

You'll also have to think about what you'd like to show your user if they tried to change the url to a category that doesn't exist, or have any reviews associated with it.

2022-09-28 14:07 UTC, mallionaire commented on src/App.js
> +          <h2>The Table-Top Appraisal Shop&trade;</h2>
Such fine marketing! 😄

2022-09-28 14:07 UTC, mallionaire commented on src/Components/AllReviews.jsx
> +          console.log(11111, review);
Ahem... what is this 🙄

2022-09-28 14:07 UTC, mallionaire commented on src/Components/CategoriesPage.jsx
> +    fetch("https://fe-games.herokuapp.com/api/categories")
Would really recommend a refactor to axios, and extracting to an utils/api.js

2022-09-28 14:07 UTC, mallionaire commented on src/Components/ReviewCard.jsx
> +  console.log(22222, review);
Not another one...

2022-09-28 14:07 UTC, mallionaire commented on src/Components/ReviewPage.jsx
> +  console.log(666666, review);
Don't make me say it again Ross!

2022-09-28 14:07 UTC, mallionaire commented on src/Components/SingleCategory.jsx
> +                  <u>{review.category}</u>
I don;t think this is needed for each item, a little jarring for the user to see it over and over.

2022-09-28 14:07 UTC, mallionaire commented on src/utils/api.js
> +export const fetchReviewCard = (review_id) => {
Ditto above, this fetches a singleReview, not a reviewCard, you're displaying the info on a review card

2022-09-28 14:07 UTC, mallionaire commented on src/utils/api.js
> +import axios from "axios";
Please use these functions 👍

2022-09-28 14:07 UTC, mallionaire commented on src/Components/SingleCategory.jsx
> +                height="200"
Personally I'd extract the CSS, your components will bloat very quickly otherwise.

2022-09-29 08:56 UTC, emilyb93 commented on src/Components/CategoriesPage.jsx
> +      });
Lets extract this into an axios function in your api like we have with your others

2022-09-29 08:58 UTC, emilyb93 approved these changes
Extract your function from CategoriesPage to the api.js file, remove ANY console.logs floating about and this is good to go

2022-09-29 09:54 UTC, merged